### ISSUE TITLE
AFLI-Calib Implamentation

### ISSUE THREAD

**Issue by StepTurtle** [Taeyoung96/Awesome-LiDAR-IMU-calibration#1]
Hey, I'm not sure if this is the right place to ask this question, and I apologize if it's not. In the AFLI-Calib paper, they mentioned that they implemented the method in C++. I was wondering if they are considering making it open-source, do you have any opinion or knowledge about that?

**Comment by Taeyoung96** [comment]
@StepTurtle   
Thanks for your interest in my work! Actually, I'm not the author of AFLI-Calib. 
So, I haven't found any open source in C++ either. If you find it, please send a pull request to this repository. :smile:

**Comment by StepTurtle** [comment]
Thanks for your response, i will share with you if I find any source code. ⭐

**Comment by wwtinwhu** [comment]
@Taeyoung96 Thanks for your great work! 
@StepTurtle  AFLI-Calib is now open-sourced ! Thanks for your interest!  Link: https://github.com/DCSI2022/AFLI_Calib

**Comment by StepTurtle** [comment]
Really nice to hear that. Many thanks for your open-source work.
